name: Run Daily Script and Update README

on:
  # 每天凌晨 3 点 (UTC 时间) 自动运行
  schedule:
    - cron: "0 3 * * *"

  # 允许手动触发
  workflow_dispatch:

  # 当推送到 main 分支时也运行
  push:
    branches:
      - main

  # PR 到 main 分支时也运行
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Python Script and Update README

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv tabulate

      - name: Run Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_TYPE: ${{ secrets.LOGIN_TYPE }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          python task.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check if README.md was updated
        run: |
          git diff

          git add README.md

          if git diff --cached --exit-code; then
            echo "⚠️ 没有变化，跳过提交"
          else
            git commit -m "Auto update README.md [skip ci]"
            git push
          fi