name: Run Daily Script and Update README

on:
  # 每天早上10 点 UTC 时间运行和晚上7点运行
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 19 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Python Script and Update README

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv tabulate markdown

      - name: Run Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_TYPE: ${{ secrets.LOGIN_TYPE }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          SMTP_SERVER: ${{  secrets.SMTP_SERVER }}
          SMTP_PORT: ${{secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL}}
          SENDER_PASSWORD: ${{secrets.SENDER_PASSWORD}}
          RECEIVER_EMAIL: ${{secrets.RECEIVER_EMAIL}}
        run: |
          python task.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Auto commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update README"
          branch: main
          commit_user_name: github-actions
          commit_user_email: github-actions@github.com
          file_pattern: README.md
          pull_before_commit: true