name: Run Daily Script and Update README

on:
  # 每天凌晨 3 点 (UTC 时间) 自动运行
  schedule:
    - cron: "0 3 * * *"

  # 允许手动触发
  workflow_dispatch:

  # 当推送到 main 分支时也运行
  push:
    branches:
      - main

  # PR 到 main 分支时也运行
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Python Script and Update README

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv tabulate

      - name: Run Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_TYPE: ${{ secrets.LOGIN_TYPE }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          python task.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Git Pull Before Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase --autostash origin main

          - name: 推送新 README.md
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: "Auto update README"
              branch: main
              commit_user_name: github-actions
              commit_user_email: github-actions@github.com