name: Run Daily Script

on:
  schedule:
    - cron: "0 3 * * *"  # 每天 UTC 时间凌晨 3 点运行
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv tabulate

      - name: Run script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_TYPE: ${{ secrets.LOGIN_TYPE }}
          LOGIN_URL: ${{secrets.LOGIN_URL}}
          API_BASE_URL: ${{secrets.API_BASE_URL}}

        run: |
          python task.py